project:
  type: book
  output-dir: _build

book:
  title: "Cma"
  author: "LSYS"
  # date: "10/30/2023"
  chapters:
    - index.qmd
  downloads: [pdf, epub, docx]
  navbar:
    title: "Overview"
    right:  
      - icon: house-up-fill
        href: https://www.lucasshen.com
        aria-label: Home directory
        target: _blank
      - icon: github
        href: https://github.com/lsys/cma
        aria-label: GitHub 
        target: _blank
  sharing: [twitter, facebook, linkedin]
  search:
    location: navbar
    type: overlay
  

bibliography: assets/references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    smooth-scroll: true
    toc-title: "On this page"
    sidebar: false
    anchor-sections: true
    number-sections: false
    grid:
      body-width: 625px
      margin-width: 350px
    reference-location: margin
    html-math-method: mathjax

  pdf:
    documentclass: scrreprt
    include-in-header:
      - file: assets/packages.tex
      - assets/macros.tex
    keep-tex: false

  epub: 
    include-before-header: assets/macros.tex


