project:
  type: book
  output-dir: _build

book:
  title: "Cma"
  author: "LSYS"
  # date: "10/30/2023"
  chapters:
    - index.qmd
  downloads: [pdf, epub, docx]
  navbar:
    title: "Overview"
  sharing: [twitter, facebook, linkedin]
  search:
    location: navbar
    type: overlay
  

bibliography: assets/references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    smooth-scroll: true
    toc-title: "On this page"
    sidebar: false
    anchor-sections: true
    number-sections: false
    grid:
      body-width: 625px
      margin-width: 350px
    reference-location: margin
    # include-in-header:
    #   - file: assets/macros.html      
    # citation-location: margin

  # pdf:
  #   documentclass: scrreprt
  # epub: default
  # docx: default



# format: 
#     html:
#       include-in-header:
#          - file: macros.html
#     pdf:
#       include-in-header:
#          - text: |
#                \newcommand{\foo}{E=mc^{2}}
