project:
  type: book
  output-dir: _build

book:
  title: "Cma"
  author: "LSYS"
  # date: "10/30/2023"
  chapters:
    - index.qmd
  downloads: [pdf, epub, docx]
  navbar:
    title: "Overview"
    right:
      - icon: github
        href: https://github.com/lsys/cma
        aria-label: GitHub    
  sharing: [twitter, facebook, linkedin]
  search:
    location: navbar
    type: overlay
  

bibliography: assets/references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    smooth-scroll: true
    toc-title: "On this page"
    sidebar: false
    anchor-sections: true
    number-sections: false
    grid:
      body-width: 625px
      margin-width: 350px
    reference-location: margin

  pdf:
    documentclass: default
  epub: default
  docx: default
